CREATE TABLE IF NOT EXISTS flight (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  airline VARCHAR(255) NOT NULL,
  origin VARCHAR(100) NOT NULL,
  destination VARCHAR(100) NOT NULL,
  departure_time TIMESTAMP NULL,
  arrival_time TIMESTAMP NULL,
  trip_type VARCHAR(20) NOT NULL, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS booking (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  flight_id BIGINT NOT NULL,
  user_email VARCHAR(255) NOT NULL,
  booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(30) NOT NULL, 
  is_returned BOOLEAN DEFAULT FALSE, 
  FOREIGN KEY (flight_id) REFERENCES flight(id)
);